FROM quay.io/fedora/fedora-bootc:latest

RUN dnf5 install -y htop age && \
    dnf5 install -y --setopt=install_weak_deps=False neovim && \
    dnf5 clean all && \
    echo "EDITOR=NVIM" >> /etc/profile

RUN systemctl enable podman.socket podman-auto-update.timer

RUN echo "ampere" > /etc/hostname

RUN bootc container lint
