name: Build hel image
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build bootc image
    runs-on: ubuntu-24.04
    container:
      image: mgoltzsche/podman:latest
      options: --privileged --security-opt seccomp=unconfined

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set env
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: sudo podman build -t ghcr.io/neiios/homelab-hel:$COMMIT_HASH ./hosts/hel

      - name: Login to ghcr
        run: sudo podman login --verbose --password '${{ secrets.GITHUB_TOKEN }}' --username neiios ghcr.io

      - name: Push built image
        run: |
          sudo podman tag ghcr.io/neiios/homelab-hel:$COMMIT_HASH ghcr.io/neiios/homelab-hel:latest
          sudo podman push ghcr.io/neiios/homelab-hel:$COMMIT_HASH
          sudo podman push ghcr.io/neiios/homelab-hel:latest
