name: Build ampere image
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build bootc image
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set env
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Install podman and friends
        run: sudo apt-get install -y podman buildah skopeo

      - name: Build image
        run: sudo podman build -t ghcr.io/neiios/homelab-ampere:$COMMIT_HASH ./hosts/ampere

      - name: Login to ghcr
        run: sudo podman login --verbose --password '${{ secrets.GITHUB_TOKEN }}' --username neiios ghcr.io

      - name: Push built image
        run: |
          sudo podman tag ghcr.io/neiios/homelab-ampere:$COMMIT_HASH ghcr.io/neiios/homelab-ampere:latest
          sudo podman push ghcr.io/neiios/homelab-ampere:$COMMIT_HASH
          sudo podman push ghcr.io/neiios/homelab-ampere:latest
